spring:
 cloud:
   gateway:
     discovery:
       locator:
         enabled: true
         lower-case-service-id: true
     routes:
       - id: USERSERVICE
         uri: lb://userservice
         predicates:
           - Path=/userservice/**
         


       - id: PRODUCTSERVICE
         uri: lb://productservice
         predicates:
           - Path=/productservice/**
         


 application:
   name: LOCALORDERGATEWAY

eureka:
  client:
    eureka-server-port: 8761
    
    
logging:
  level:
    root: info
    org.springframework.cloud.gateway: trace
    org.springframework.cloud.gateway.route.CompositeRouteDefinitionLocator: info
